"""
app/main.py — FastAPI Application Entry Point

This is where everything is assembled:
  - App is created with metadata for auto-generated OpenAPI docs
  - Middleware is registered (CORS, logging, rate limiting)
  - Exception handlers are registered
  - All API routers are mounted under /api/v1
  - Startup/shutdown lifecycle events manage DB and Redis connections

Run with: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
"""

import structlog
from fastapi import FastAPI
from fastapi.responses import JSONResponse

from app.config import settings
from app.core.exceptions import register_exception_handlers
from app.core.middleware import register_middleware
from app.database import close_db, init_db
from app.redis_client import close_redis

logger = structlog.get_logger()

# ─── App Instance ─────────────────────────────────────────────────────────────
app = FastAPI(
    title=settings.APP_NAME,
    description="""
# 🎓 AI Student Performance Analysis Platform

A scalable, AI-powered platform for student performance tracking and analysis.

## Features
- **🔐 JWT Authentication** with role-based access control
- **📊 Performance Analytics** with subject and topic-level breakdown
- **🤖 AI Reports** generated by Llama 70B
- **📄 OCR Processing** for question papers (PaddleOCR + Tesseract)
- **🎙️ Speech Analysis** for classroom recordings (Whisper STT)
- **📉 Weak Topic Detection** with AI-powered root cause analysis
- **💡 Personalized Recommendations** for each student

## AI Models
- **Llama 70B** (via Ollama) — Report generation, question parsing, classroom analysis
- **NVIDIA Nemotron Embed VL 1B V2** — Question embeddings and topic classification
- **OpenAI Whisper** (local) — Speech-to-text transcription

## Authentication
Include the JWT access token in the `Authorization` header:
```
Authorization: Bearer <access_token>
```
    """,
    version="1.0.0",
    docs_url="/docs" if settings.DEBUG else None,  # Disable docs in production
    redoc_url="/redoc" if settings.DEBUG else None,
    openapi_url="/openapi.json" if settings.DEBUG else None,
    contact={
        "name": "StudentAI Platform",
        "email": "support@studentai.example.com",
    },
    license_info={
        "name": "MIT",
    },
)

# ─── Middleware ───────────────────────────────────────────────────────────────
register_middleware(app)

# ─── Exception Handlers ───────────────────────────────────────────────────────
register_exception_handlers(app)


# ─── Lifecycle Events ─────────────────────────────────────────────────────────
@app.on_event("startup")
async def startup_event():
    """
    Called once when the server starts.
    - Verifies DB connection
    - In development: creates tables (production uses Alembic)
    - Logs startup info
    """
    logger.info(
        "Starting StudentAI Platform",
        env=settings.APP_ENV,
        debug=settings.DEBUG,
        llm_model=settings.LLAMA_MODEL,
    )

    if settings.APP_ENV == "development":
        # Only auto-create tables in development
        # Production: always use `alembic upgrade head`
        try:
            await init_db()
            logger.info("Database tables initialized (development mode)")
        except Exception as e:
            logger.warning("DB init skipped", error=str(e))


@app.on_event("shutdown")
async def shutdown_event():
    """Gracefully close DB and Redis connections on server shutdown."""
    logger.info("Shutting down StudentAI Platform")
    await close_db()
    await close_redis()


# ─── API Routers ──────────────────────────────────────────────────────────────
# All routes are versioned under /api/v1
# This allows future /api/v2 without breaking existing clients

from app.api.v1 import (
    auth,
    students,
    ocr,
    speech,
    reports,
    attendance,
    dashboards,
    # Phase 2 — Intelligence Platform routes
    behavioral,
    sports,
    health,
    intelligence_profile,
    teacher_actions,
)

API_PREFIX = "/api/v1"

# ── Phase 1: Core Platform ─────────────────────────────────────────────────
app.include_router(auth.router, prefix=API_PREFIX)
app.include_router(students.router, prefix=API_PREFIX)
app.include_router(ocr.router, prefix=API_PREFIX)
app.include_router(speech.router, prefix=API_PREFIX)
app.include_router(reports.router, prefix=API_PREFIX)
app.include_router(attendance.router, prefix=API_PREFIX)
app.include_router(dashboards.router, prefix=API_PREFIX)

# ── Phase 2: Digital Intelligence Profile ─────────────────────────────────
app.include_router(behavioral.router, prefix=API_PREFIX)
app.include_router(sports.router, prefix=API_PREFIX)
app.include_router(health.router, prefix=API_PREFIX)
app.include_router(intelligence_profile.router, prefix=API_PREFIX)
app.include_router(teacher_actions.router, prefix=API_PREFIX)


# ─── Health Check ─────────────────────────────────────────────────────────────
@app.get("/health", tags=["System"], summary="Health check for load balancer/Docker")
async def health_check():
    """
    Used by Docker, Kubernetes, and load balancers to verify the app is running.
    Returns DB and Redis connectivity status.
    """
    from app.database import engine
    import redis.asyncio as aioredis
    from app.redis_client import get_redis_pool

    db_ok = False
    redis_ok = False

    try:
        async with engine.connect() as conn:
            await conn.execute(__import__("sqlalchemy", fromlist=["text"]).text("SELECT 1"))
        db_ok = True
    except Exception:
        pass

    try:
        r = aioredis.Redis(connection_pool=get_redis_pool())
        await r.ping()
        redis_ok = True
    except Exception:
        pass

    status_code = 200 if (db_ok and redis_ok) else 503
    return JSONResponse(
        status_code=status_code,
        content={
            "status": "healthy" if (db_ok and redis_ok) else "degraded",
            "services": {
                "database": "ok" if db_ok else "error",
                "redis": "ok" if redis_ok else "error",
                "api": "ok",
            },
            "version": "1.0.0",
            "environment": settings.APP_ENV,
        },
    )


@app.get("/", tags=["System"])
async def root():
    return {
        "name": settings.APP_NAME,
        "version": "1.0.0",
        "docs": "/docs" if settings.DEBUG else "Disabled in production",
        "health": "/health",
    }
