"""
app/models/mixins.py — Shared Column Mixins

Instead of repeating id/created_at/updated_at in every model,
we define them once as a mixin. This is a clean, DRY pattern.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDMixin:
    """
    UUID primary key.
    Why UUID instead of integer?
      - Globally unique: safe to expose in APIs (no sequential guessing)
      - Works in distributed systems without coordination
      - gen_random_uuid() is generated by PostgreSQL, not Python,
        ensuring uniqueness even with concurrent inserts
    """
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """
    Automatic created_at / updated_at timestamps.
    server_default / onupdate are DB-side — accurate even if Python
    code forgets to set them.
    """
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """
    Soft delete: records are never physically deleted.
    Instead, deleted_at is set. Queries filter WHERE deleted_at IS NULL.
    
    Benefits:
      - Audit trail preserved
      - Data recovery possible
      - Analytics are never broken by missing FK references
    """
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self) -> None:
        self.deleted_at = datetime.now(timezone.utc)
