"""
app/models/recommendation.py — Personalized Study Recommendations
"""

import enum
import uuid

from sqlalchemy import Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.mixins import TimestampMixin, UUIDMixin


class RecommendationType(str, enum.Enum):
    TOPIC_REVIEW = "topic_review"
    PRACTICE_PROBLEMS = "practice_problems"
    VIDEO_RESOURCE = "video_resource"
    PEER_DISCUSSION = "peer_discussion"
    TEACHER_HELP = "teacher_help"
    REVISION_SCHEDULE = "revision_schedule"


class RecommendationStatus(str, enum.Enum):
    PENDING = "pending"      # Not yet seen by student
    VIEWED = "viewed"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    DISMISSED = "dismissed"


class Recommendation(UUIDMixin, TimestampMixin, Base):
    """
    AI-generated personalized recommendation for a student.
    
    Generated by recommendation_engine.py based on:
      - Current weak topics
      - Learning pace (time between assessments vs. score improvement)
      - Student's historical response to recommendations
      - Curriculum sequence (prerequisite topics first)
    """
    __tablename__ = "recommendations"

    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("students.id"), nullable=False, index=True
    )
    topic_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("topics.id"), nullable=True
    )
    weak_topic_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("weak_topics.id"), nullable=True
    )

    recommendation_type: Mapped[RecommendationType] = mapped_column(
        Enum(RecommendationType), nullable=False, index=True
    )
    status: Mapped[RecommendationStatus] = mapped_column(
        Enum(RecommendationStatus), default=RecommendationStatus.PENDING
    )

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Structured action plan from AI
    # {"steps": [...], "resources": [...], "estimated_hours": 3}
    action_plan: Mapped[dict | None] = mapped_column(JSONB)
    
    # Priority: 1 (highest) → 5 (lowest)
    priority: Mapped[int] = mapped_column(Integer, default=3)
    
    # Estimated impact on score if followed
    expected_score_improvement: Mapped[float | None] = mapped_column(Float)

    student: Mapped["Student"] = relationship(back_populates="recommendations")
    topic: Mapped["Topic | None"] = relationship(back_populates="recommendations")

    def __repr__(self) -> str:
        return f"<Recommendation {self.recommendation_type.value} priority={self.priority}>"
